INSERT INTO users (username, password) VALUES
  ('lionelmessi', '12345678'),
  ('marysmith', '12345678'),
  ('alexjones', '12345678'),
  ('lindabrown', '12345678'),
  ('emilywhite', '12345678');

INSERT INTO decks (user_id, d_name, d_description, d_category) VALUES
  (1, 'JavaScript Basics', 'A collection of flashcards to help understand basic JavaScript concepts like variables, loops, and functions.', 'Technology'),
  (1, 'ReactJS Fundamentals', 'A collection of flashcards to help master the basics of ReactJS, including JSX, components, and hooks.', 'Technology'),
  (2, 'French Vocabulary', 'A set of flashcards to practice essential French vocabulary for beginners.', 'Language Learning'),
  (2, 'World History Overview', 'A collection of flashcards covering key events and figures in world history.', 'Education'),
  (3, 'Python Programming', 'Flashcards covering basic and advanced Python programming concepts such as data types, loops, and OOP.', 'Technology'),
  (3, 'Geography Quiz', 'A set of flashcards with questions about countries, capitals, and famous landmarks around the world.', 'Education'),
  (4, 'Web Development', 'Flashcards that cover web development topics including HTML, CSS, and JavaScript basics.', 'Technology'),
  (4, 'Art History', 'A collection of flashcards with important art movements, artists, and techniques throughout history.', 'Education'),
  (5, 'Spanish Grammar', 'Flashcards for learning the fundamentals of Spanish grammar, including tenses and sentence structure.', 'Language Learning'),
  (5, 'American Presidents', 'A collection of flashcards featuring facts about U.S. presidents, their policies, and historical context.', 'History');

INSERT INTO flashcards (deck_id, f_title, f_detail) VALUES
  (1, 'What is a variable?', 'A variable is a container for storing data values.'),
  (1, 'What is a function?', 'A function is a block of code designed to perform a particular task.'),
  (1, 'What does "let" do in JavaScript?', 'The "let" keyword is used to declare variables in JavaScript.'),
  (1, 'What is a loop?', 'A loop is used to repeatedly run a block of code as long as a specified condition is true.'),
  (2, 'What is JSX?', 'JSX is a syntax extension for JavaScript that looks similar to XML or HTML.'),
  (2, 'What is a React component?', 'A React component is a JavaScript function or class that optionally accepts inputs and returns a React element that describes how a UI should appear.'),
  (2, 'What is the useState hook?', 'useState is a Hook that lets you add React state to function components.'),
  (3, 'How do you say "hello" in French?', 'Bonjour.'),
  (3, 'What does "Merci" mean?', 'Merci means "thank you" in French.'),
  (3, 'What is the French word for "book"?', 'Livre.'),
  (4, 'When did World War I begin?', 'World War I began in 1914.'),
  (4, 'Who was the first president of the United States?', 'George Washington was the first president of the United States.'),
  (4, 'What was the cause of the Cold War?', 'The Cold War was primarily caused by ideological differences between the USA and the Soviet Union, especially after World War II.'),
  (5, 'What is a list in Python?', 'A list is a collection which is ordered and changeable.'),
  (5, 'What is the difference between a tuple and a list in Python?', 'A tuple is immutable, while a list is mutable.'),
  (5, 'What does "def" mean in Python?', 'The "def" keyword is used to declare a function in Python.'),
  (6, 'What is the capital of France?', 'Paris is the capital of France.'),
  (6, 'Which country has the largest population?', 'China has the largest population in the world.'),
  (6, 'What is the longest river in the world?', 'The Nile is often considered the longest river in the world, though some claim the Amazon River is longer.'),
  (7, 'What is HTML?', 'HTML stands for HyperText Markup Language, used to create the structure of web pages.'),
  (7, 'What does CSS stand for?', 'CSS stands for Cascading Style Sheets, used for styling HTML elements.'),
  (7, 'What is JavaScript used for in web development?', 'JavaScript is used to create interactive effects within web browsers.'),
  (8, 'Who painted the Mona Lisa?', 'The Mona Lisa was painted by Leonardo da Vinci.'),
  (8, 'What is Impressionism?', 'Impressionism is an art movement that began in France in the 19th century, characterized by a focus on light and color.'),
  (8, 'What does "Cubism" refer to?', 'Cubism is an early-20th-century art movement that abandoned perspective and used fragmented shapes to represent objects.'),
  (9, 'How do you say "I am" in Spanish?', 'Yo soy.'),
  (9, 'What is the past tense of "hablar" (to speak)?', 'The past tense of hablar is "hablé" for the first person singular.'),
  (9, 'What does "el perro" mean?', 'El perro means "the dog" in Spanish.'),
  (10, 'Who was the 16th president of the United States?', 'Abraham Lincoln was the 16th president of the United States.'),
  (10, 'What was Franklin D. Roosevelt known for?', 'Franklin D. Roosevelt was known for leading the United States during the Great Depression and World War II.'),
  (10, 'Who was the first woman to run for president in the U.S.?', 'The first woman to run for president in the U.S. was Victoria Woodhull in 1872.');
