CREATE TABLE IF NOT EXISTS decks (
  d_id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  d_name VARCHAR(100) NOT NULL,
  d_description TEXT,
  d_category VARCHAR(50),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS flashcards (
  f_id INT AUTO_INCREMENT PRIMARY KEY,
  deck_id INT NOT NULL,
  f_title TEXT NOT NULL,
  f_detail TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (deck_id) REFERENCES decks(d_id) ON DELETE CASCADE
)